WinWaitActive("LAN1-2 Install Program")
Sleep(4000)
ControlFocus("LAN1-2 Install Program","","&Next >")
Sleep(2000)
ControlClick("LAN1-2 Install Program","","&Next >")
Sleep(2000)
ControlFocus("LAN1-2 Install Program","","&Next >")
Sleep(2000)
ControlClick("LAN1-2 Install Program","","&Next >")
Sleep(2000)
ControlFocus("LAN1-2 Install Program","","&Yes")
Sleep(2000)
ControlClick("LAN1-2 Install Program","","&Yes")
Sleep(2000)
ControlFocus("LAN1-2 Install Program","","&Start")
Sleep(2000)
ControlClick("LAN1-2 Install Program","","&Start")
Local $i=1;
Do
sleep($i=$i+1)
ControlFocus("LAN1-2 Install Program","","E&xit")
Until (ControlFocus("LAN1-2 Install Program","","E&xit")=1)
Sleep(2000)
ControlClick("LAN1-2 Install Program","","E&xit")